[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.0"
ir = { path = "../ir" }
onnx = { path = "../onnx" }
prost = { version = "0.11" }
