[package]
name = "steelix-onnx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
prost = "0.11"
thiserror = "1.0.35"

[build-dependencies]
prost-build = "0.11"
